# Generated by Django 5.0.2 on 2024-03-13 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Schedules",
            "0002_inviteeavailabletimes_owneravailabletimes_schedule_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="invitee_available_times",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Schedules.inviteeavailabletimes",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="owner_available_times",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Schedules.owneravailabletimes",
            ),
        ),
    ]
