# Generated by Django 5.0.2 on 2024-03-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0003_alter_schedule_invitee_available_times_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="invitee_available_times",
        ),
        migrations.RemoveField(
            model_name="owneravailabletimes",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="owner_available_times",
        ),
        migrations.DeleteModel(
            name="InviteeAvailableTimes",
        ),
        migrations.DeleteModel(
            name="OwnerAvailableTimes",
        ),
    ]
