# Generated by Django 5.0.2 on 2024-03-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0004_remove_schedule_invitee_available_times_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="invitees",
        ),
        migrations.AddField(
            model_name="schedule",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_invitee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="finalized",
            field=models.BooleanField(default=False),
        ),
    ]
