# Generated by Django 5.0.2 on 2024-03-13 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0005_remove_schedule_invitees_schedule_invitee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
