# Generated by Django 5.0.3 on 2024-03-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0007_calendar_availability_invitee_event_delete_schedule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitee",
            old_name="invitee",
            new_name="contact_id",
        ),
    ]
