# Generated by Django 5.0.3 on 2024-03-30 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0008_rename_invitee_invitee_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitee",
            name="random_link_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
