# Generated by Django 5.0.3 on 2024-03-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0009_invitee_random_link_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitee",
            old_name="contact_id",
            new_name="contact",
        ),
    ]
