# Generated by Django 5.0.3 on 2024-03-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0010_rename_contact_id_invitee_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitee",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitees",
                to="Schedules.calendar",
            ),
        ),
        migrations.RemoveField(
            model_name="invitee",
            name="selected_availability",
        ),
        migrations.AddField(
            model_name="invitee",
            name="selected_availability",
            field=models.ManyToManyField(
                blank=True, null=True, to="Schedules.availability"
            ),
        ),
    ]
