# Generated by Django 5.0.3 on 2024-03-31 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Schedules", "0011_alter_invitee_calendar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitee",
            name="selected_availability",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "calendar": models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitees",
                        to="Schedules.calendar",
                    )
                },
                to="Schedules.availability",
            ),
        ),
    ]
