# Generated by Django 5.0.3 on 2024-03-31 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contacts", "0002_contact_delete_contacts"),
        ("Schedules", "0014_alter_invitee_selected_availability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_time",
        ),
        migrations.AddField(
            model_name="event",
            name="timeslot",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="Schedules.availability",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invitee",
            name="calendar",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitees",
                to="Schedules.calendar",
            ),
        ),
        migrations.AlterField(
            model_name="invitee",
            name="contact",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="Contacts.contact",
            ),
        ),
    ]
